<div class="block block-list block-viewed">
    <div class="block-title">
        <strong><span><?=$this->__('Recently Sold Products');?></span></strong>
    </div>
    <ul class="products-grid products-grid--max-3-col">
        <?php foreach($products_list as $_item): ?>
            <li class="item">
                <a href="<?=$_item->getProductUrl();?>" title="<?=$this->escapeHtml($_item->getName());?>" class="product-image">
                    <?php $_imgSize = 260; ?>
                    <img src="<?=$this->helper('catalog/image')->init($_item, 'small_image')->resize($_imgSize);?>" alt="<?=$this->escapeHtml($this->getName());?>" />
                </a>
            </li>
         <?php endforeach; ?>
    </ul>
</div>