<div class="block block-list block-viewed">
    <div class="block-title">
        <strong><span><?=$this->__('Recently Sold Products');?></span></strong>
    </div>
    <div class="block-content">
        <ol id="recently-viewed-items" class="mini-products-list">
            <?php foreach($products_list as $_item): ?>
                <li class="item">
                    <a href="<?=$_item->getProductUrl();?>">
                        <span class="product-image"><img src="<?=$this->helper('catalog/image')->init($_item, 'thumbnail')->resize(50, 50)->setWatermarkSize('30x10');?>" width="50" height="50" alt="<?=$this->escapeHtml($this->getName());?>" /></span>
                    </a>
                    <div class="product-details">
                        <p>
                            <a href="<?=$_item->getProductUrl();?>"><?=$_item->getName();?></a>
                        </p>
                        <p>
                            <?=Mage::helper('core')->currency($_item->getPrice(),true,false);?>
                        </p>
                        <p>
                            <a href="<?=Mage::helper('checkout/cart')->getAddUrl($_item);?>"><?=$this->__('Add to cart');?></a>
                        </p>
                    </div>
                </li>
            <?php endforeach;?>
        </ol>
    </div>
</div>
