<div class="box-account box-info">
    <hr />
    <div class="col2-set">
        <div class="col-1">
            <div class="box">
                <div class="box-content">
                    <p style="width: 150px;">
                        <strong><?=$this->__('Your level');?>: </strong> <?=$this->getDiscountLevel();?>
                    </p>
                    <p style="width: 150px;">
                        <strong><?=$this->__('Your discount');?>: </strong> <?=$this->getCustomerDiscount();?>%
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>