<?php $this->setPriceDataObject($this->getSource()) ?>

<?php if ((float) $this->getSource()->getCostumerCreditAmount()): ?>
    <tr>
        <td class="label"><?php echo Mage::helper('costumercredit')->__('Costumer Credit') ?></td>
        <td>222222222222222222
            <?php echo $this->displayPrices($this->getSource()->getBaseCostumerCreditAmount(), $this->getSource()->getCostumerCreditAmount()); ?>
        </td>
    </tr>
<?php endif; ?>