<?php if($this->getSource() instanceof Mage_Sales_Model_Order): ?>
    <?php if ((float)$this->getSource()->getDiscountAmountRefunded() > 0): ?>
        <tr>
            <td class="label"><strong><?php echo Mage::helper('veles_discounts')->__('Order Discount !') ?></strong></td>
            <td><strong><?php echo $this->getSource()->getDiscountAmountRefunded(); ?></strong></td>
        </tr>
    <?php endif; ?>
<?php else: ?>
    <?php if ((float)$this->getSource()->getDiscountAmount()): ?>
        <tr>
            <td class="label"><strong><?php echo Mage::helper('veles_discounts')->__('Order Discount') ?></strong></td>
            <td><strong><?php echo $this->getSource()->getDiscountAmount(); ?></strong></td>
        </tr>
    <?php endif;  ?>
<?php endif; ?>

