<?php $this->setPriceDataObject($this->getSource()) ?>
<?php if ((float) $this->getSource()->getDiscountAmount()): ?>
    <tr>
        <td class="label"><?php echo Mage::helper('veles_discounts')->__('Discount') ?></td>
        <td>
            <?php echo $this->displayPrices($this->getSource()->getBaseDiscountAmount(), $this->getSource()->getDiscountAmount()); ?>
        </td>
    </tr>
<?php endif; ?>