<div class="box-account box-info">
    <div class="box-head">
        <h2>Customer Credit Information</h2>
    </div>
    <div class="col2-set">
        <div class="col-1">
            <div class="box">
                <div class="box-content">
                    <p>
                        <strong>Bonuses, you have:</strong> <?=$customer_credits;?>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>