
<?php $quote = Mage::getSingleton('checkout/cart')->getQuote(); ?>
<form id="discount-coupon-form" action="<?php echo $this->getUrl('discounts/cart/couponPost') ?>" method="post">
    <div class="discount">
        <div class="discount-form">
            <label for="coupon_code"><?php echo $this->__($this->getCouponMess()) ?></label>
            <input type="hidden" name="remove" id="remove-coupone" value="0" />
            <div class="field-wrapper">
                <input class="input-text" type="text" id="coupon_code" name="coupon_code" value="<?php echo $this->escapeHtml($quote->getVdCouponCode()) ?>" />
                <div class="button-wrapper">
                    <button type="button" title="<?php echo $this->__('Apply') ?>" class="button2" onclick="discountForm.submit(false)" value="<?php echo $this->__('Apply') ?>"><span><span><?php echo $this->__('Apply') ?></span></span></button>
                    <?php if(strlen($quote->getVdCouponCode())): ?>
                        <button type="button" title="<?php echo $this->__('Cancel') ?>" class="button2 cancel-coupon" onclick="discountForm.submit(true)" value="<?php echo $this->__('Cancel') ?>"><span><span><?php echo $this->__('Cancel') ?></span></span>
                        </button>
                    <?php endif;?>
                </div>
            </div>
        </div>
    </div>
</form>
<script type="text/javascript">
    //<![CDATA[
    var discountForm = new VarienForm('discount-coupon-form');
    discountForm.submit = function (isRemove) {
        if (isRemove) {
            $('coupon_code').removeClassName('required-entry');
            $('remove-coupone').value = "1";
        } else {
            $('coupon_code').addClassName('required-entry');
            $('remove-coupone').value = "0";
        }
        return VarienForm.prototype.submit.bind(discountForm)();
    }
    //]]>
</script>
