<?php
    $mainFaqUrl = Mage::getUrl('faq');
?>
<div class="page-title">
    <h1><?=$questionItem->getTitle();?></h1>
</div>
<div class="content cms-page-view " style="margin: 0px 0px 100px 20px;">
    <div class="std" style="border-bottom: 1px solid #e6e6e6; padding-bottom: 40px; padding-top: 10px;">
        <h2>Question</h2>
        <?php echo $questionItem->getQuestion(); ?>
    </div>
    <div class="std" style="border-bottom: 1px solid #e6e6e6; padding-bottom: 40px; padding-top: 10px;">
        <h2>Answer</h2>
        <?php echo $questionItem->getAnswer(); ?>
    </div>
</div>

<div>
    <a href="<?=$mainFaqUrl;?>">< Create Your Own Question</a>
</div>